# Generated by Django 5.1.6 on 2025-02-09 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="User",
            new_name="user",
        ),
    ]
